---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: anza-labs-base
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: lke-cluster-apps
  path: "./apps/anza-labs/base"
  prune: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: anza-labs-lubelogger
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: lke-cluster-apps
  path: "./apps/anza-labs/lubelogger"
  prune: true
  timeout: 10m
  dependsOn:
  - name: anza-labs-base
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-base
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: lke-cluster-apps
  path: "./apps/capi/base"
  prune: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-core
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: lke-cluster-apps
  path: "./apps/capi/core"
  prune: true
  timeout: 10m
  dependsOn:
  - name: capi-base
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-k0smotron
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: lke-cluster-apps
  path: "./apps/capi/k0smotron"
  prune: true
  timeout: 10m
  dependsOn:
  - name: capi-base
  - name: capi-core
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers-cloudflare
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: lke-cluster-apps
  path: "./apps/cert-manager/issuers/cloudflare"
  prune: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-base
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: lke-cluster-apps
  path: "./apps/cilium/base"
  prune: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-tetragon
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: lke-cluster-apps
  path: "./apps/cilium/tetragon"
  prune: true
  timeout: 10m
  dependsOn:
  - name: cilium-base
