---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-operator
spec:
  path: "./configs/capi/operator"
  dependsOn:
  - name: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-core
spec:
  path: "./configs/capi/core"
  dependsOn:
  - name: cert-manager
  - name: capi-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-k0smotron
spec:
  path: "./configs/capi/k0smotron"
  dependsOn:
  - name: cert-manager
  - name: capi-operator
  - name: capi-core
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: capi-cluster-eu-2
# spec:
#   path: "./configs/capi/clusters/eu-2"
#   dependsOn:
#   - name: capi-operator
#   - name: capi-core
#   - name: capi-k0smotron
#   - name: cert-manager
#   - name: external-secrets
#   - name: tailscale
