---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  chart:
    spec:
      chart: kyverno-policies
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kyverno-github-io-kyverno
        namespace: placeholder
      version: "3.4.1"
  interval: 30m0s
  timeout: 10m0s
  releaseName: kyverno-policies
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
