---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: eu-2
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: cp-test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteCluster
    name: eu-2
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: eu-2
spec:
  version: v1.30.4+k0s.0
  persistence:
    type: emptyDir
  service:
    type: NodePort
    apiPort: 36443
    konnectivityPort: 38132
    annotations: {}
