---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: infra
      version: "1.82.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: tailscale-operator
  targetNamespace: tailscale
  test:
    enable: true
    ignoreFailures: true
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: rollback
      remediateLastFailure: true
  values:
    apiServerProxyConfig:
      mode: "noauth"
  valuesFrom:
  - kind: Secret
    name: tailscale-oauth
    valuesKey: clientId
    targetPath: oauth.clientId
  - kind: Secret
    name: tailscale-oauth
    valuesKey: clientSecret
    targetPath: oauth.clientSecret
