---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lubelogger
spec:
  path: "./configs/public/lubelogger"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  path: "./configs/public/external-dns"
  dependsOn:
  - name: external-secrets-bitwarden
