---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repositories
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: flux-system
  path: "./repositories"
  prune: true
  timeout: 10m
