---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-backup
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: access-key
    remoteRef:
      key: "f93c7fb5-f3a7-4488-82a8-b2eb00be6b4d"
  - secretKey: secret-key
    remoteRef:
      key: "b69153a6-5208-4f58-a2fe-b2eb00be6b59"
