
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
spec:
  path: "./configs/monitoring/prometheus"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jaegertracing
spec:
  path: "./configs/monitoring/jaegertracing"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jaegertracing-jaeger
spec:
  path: "./configs/jaegertracing/jaeger"
  dependsOn:
  - name: jaegertracing
