---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
spec:
  chart:
    spec:
      chart: cluster-api-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: flux-system
      version: "0.12.0"
  interval: 1m0s
  releaseName: capi-operator
  targetNamespace: capi-operator-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
      remediateLastFailure: true
