---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger-operator
spec:
  chart:
    spec:
      chart: jaeger-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
      version: "2.57.0"
  interval: 1m0s
  releaseName: jaeger-operator
  targetNamespace: jaeger-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
