---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: "1.15.1"
  interval: 1m0s
  timeout: 10m
  releaseName: external-dns
  targetNamespace: external-dns
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    policy: sync
    provider:
      name: cloudflare
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: api-token
