---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: cluster-api-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-github-io-cluster-api-operator
        namespace: placeholder
      version: "0.19.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: capi-operator
  targetNamespace: capi-operator-system
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
