apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./flux-apps.yaml
patches:
- path: ./patches/alerts-patch.yaml
  target:
    group: notification.toolkit.fluxcd.io
    version: v1beta3
    kind: Alert
