---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-app
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: pocket-id
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs-github-io-charts
        namespace: placeholder
      version: "1.0.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: pocket-id
  targetNamespace: pocket-id-system
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  values:
    ingress:
      enabled: true
      className: contour
      host: auth.anza-labs.dev
    persistence:
      data:
        enabled: true
    backup:
      enabled: true
      secret:
        replicas:
          - region: eu-central
            bucket: backups-region-eu-1-shared
            path: /infra-eu-1/pocket-id
            endpoint: eu-central-1.linodeobjects.com
  valuesFrom:
  - kind: Secret
    name: pocket-id-backup
    valuesKey: access-key
    targetPath: backup.secret.accessKey
  - kind: Secret
    name: pocket-id-backup
    valuesKey: secret-key
    targetPath: backup.secret.secretKey
