apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-device-plugins
spec:
  interval: 5m
  url: https://github.com/anza-labs/kubelet-device-plugins
  ref:
    tag: v0.2.2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-device-plugins
spec:
  interval: 30m
  targetNamespace: kubelet-device-plugins-system
  sourceRef:
    kind: GitRepository
    name: kubelet-device-plugins
  path: "."
  prune: true
  timeout: 10m
