---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "27.1.0"
  interval: 1m0s
  timeout: 10m0s
  releaseName: prometheus
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
      remediateLastFailure: true
  values:
    alertmanager:
      enabled: true
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-pushgateway:
      enabled: true
