---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
spec:
  chart:
    spec:
      chart: tetragon
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: "1.3.0"
  interval: 1m0s
  releaseName: tetragon
  targetNamespace: kube-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
      remediateLastFailure: true
