---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
spec:
  chart:
    spec:
      chart: tetragon
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: "1.3.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: tetragon
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
      strategy: uninstall
      remediateLastFailure: true
