---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-ssh-key
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: value
    remoteRef:
      key: "d8c1b7e5-e2dd-43c6-a634-b1d400b4a188"
