---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jspolicy-app
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: jspolicy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: charts-loft-sh
        namespace: placeholder
      version: "0.2.2"
  interval: 30m0s
  timeout: 10m0s
  releaseName: jspolicy
  targetNamespace: jspolicy
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: rollback
      remediateLastFailure: true
