---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: versioned
  namespace: flux-system
spec:
  path: "./versioned/local"
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: flux-system
  prune: true
  timeout: 10m
  interval: 10m
