---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "${NODE_NAME}.${TAILNET}"
    cluster.anza-labs.dev/node-env: baremetal
  name: "${NODE_NAME}"
spec:
  type: ExternalName
  externalName: placeholder.example.com
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: "${NODE_NAME}"
spec:
  clusterName: homelab-cluster
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: "${NODE_NAME}"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: "${NODE_NAME}"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: "${NODE_NAME}"
spec:
  version: "${K0S_VERSION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: "${NODE_NAME}"
spec:
  address: "${NODE_NAME}"
  port: 22
  user: manager
  sshKeyRef:
    name: shared-key
