---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  labels:
    environment: prod
spec:
  interval: 5m0s
  url: https://github.com/anza-labs/manifests
  ref:
    tag: 'v2025-02-02.3'
