apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: infra
spec:
  interval: 30m
  path: ./apps/platform/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers-cloudflare
  namespace: infra
spec:
  dependsOn:
  - name: cert-manager
  - name: external-secrets-bitwarden
  interval: 30m
  path: ./apps/platform/cert-manager/issuers/cloudflare
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: infra
spec:
  interval: 30m
  path: ./apps/platform/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-bitwarden
  namespace: infra
spec:
  dependsOn:
  - name: external-secrets
  - name: cert-manager
  interval: 30m
  path: ./apps/platform/external-secrets/bitwarden
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: infra
spec:
  interval: 30m
  path: ./apps/platform/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-storage-version-migrator
  namespace: infra
spec:
  interval: 30m
  path: ./apps/platform/kube-storage-version-migrator
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubewarden-controller
  namespace: infra
spec:
  dependsOn:
  - name: kubewarden-crds
  interval: 30m
  path: ./apps/platform/kubewarden/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubewarden-crds
  namespace: infra
spec:
  interval: 30m
  path: ./apps/platform/kubewarden/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: infra
spec:
  interval: 30m
  path: ./apps/platform/kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: infra
spec:
  dependsOn:
  - name: kyverno
  interval: 30m
  path: ./apps/platform/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: infra
spec:
  interval: 30m
  path: ./apps/platform/reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: infra
spec:
  dependsOn:
  - name: external-secrets
  interval: 30m
  path: ./apps/platform/tailscale
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: generic-notifications
  namespace: infra
spec:
  eventMetadata: {}
  eventSeverity: info
  eventSources:
  - kind: Bucket
    name: '*'
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: HelmChart
    name: '*'
  - kind: HelmRepository
    name: '*'
  - kind: ImageRepository
    name: '*'
  - kind: ImagePolicy
    name: '*'
  - kind: ImageUpdateAutomation
    name: '*'
  - kind: OCIRepository
    name: '*'
  providerRef:
    name: discord-generic
  summary: An event has occurred in the production environment.
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-generic
  namespace: infra
spec:
  secretRef:
    name: discord-webhook
  type: discord
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  labels:
    environment: prod
  name: apps
  namespace: infra
spec:
  interval: 5m0s
  ref:
    commit: 535746ae85bbe9a5e02ac76d945668f3d4e09a65
  url: https://github.com/anza-labs/manifests
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anza-labs
  namespace: infra
spec:
  interval: 5m0s
  url: https://anza-labs.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capi-operator
  namespace: infra
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/cluster-api-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: infra
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: infra
spec:
  interval: 5m0s
  url: https://charts.external-secrets.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: infra
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: infra
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: infra
spec:
  interval: 5m0s
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: infra
spec:
  interval: 5m0s
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubewarden
  namespace: infra
spec:
  interval: 5m0s
  url: https://charts.kubewarden.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: infra
spec:
  interval: 5m0s
  url: https://kyverno.github.io/kyverno
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: infra
spec:
  interval: 5m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: infra
spec:
  interval: 5m0s
  url: https://stakater.github.io/stakater-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: infra
spec:
  interval: 5m0s
  url: https://pkgs.tailscale.com/helmcharts
