apiVersion: v1
kind: Namespace
metadata:
  name: cluster-eu-1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cluster-eu-1
spec:
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers-cloudflare
  namespace: cluster-eu-1
spec:
  dependsOn:
  - name: cert-manager
  - name: external-secrets-bitwarden
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/cert-manager/issuers/cloudflare
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: cluster-eu-1
spec:
  dependsOn:
  - name: external-secrets-bitwarden
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: cluster-eu-1
spec:
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-bitwarden
  namespace: cluster-eu-1
spec:
  dependsOn:
  - name: external-secrets
  - name: cert-manager
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/external-secrets/bitwarden
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: cluster-eu-1
spec:
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-storage-version-migrator
  namespace: cluster-eu-1
spec:
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/kube-storage-version-migrator
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubewarden-controller
  namespace: cluster-eu-1
spec:
  dependsOn:
  - name: kubewarden-crds
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/kubewarden/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubewarden-crds
  namespace: cluster-eu-1
spec:
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/kubewarden/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: cluster-eu-1
spec:
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: cluster-eu-1
spec:
  dependsOn:
  - name: kyverno
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lubelogger
  namespace: cluster-eu-1
spec:
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/public/lubelogger
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: cluster-eu-1
spec:
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: cluster-eu-1
spec:
  dependsOn:
  - name: external-secrets
  interval: 30m
  patches:
  - patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          name: "eu-1-kubeconfig"
          key: value
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2
  path: ./apps/platform/tailscale
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: infra
  timeout: 10m
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: generic-notifications
  namespace: cluster-eu-1
spec:
  eventMetadata: {}
  eventSeverity: info
  eventSources:
  - kind: Bucket
    name: '*'
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: HelmChart
    name: '*'
  - kind: HelmRepository
    name: '*'
  - kind: ImageRepository
    name: '*'
  - kind: ImagePolicy
    name: '*'
  - kind: ImageUpdateAutomation
    name: '*'
  - kind: OCIRepository
    name: '*'
  providerRef:
    name: discord-generic
  summary: An event has occurred in the production environment.
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-generic
  namespace: cluster-eu-1
spec:
  secretRef:
    name: discord-webhook
  type: discord
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  labels:
    environment: prod
  name: apps
  namespace: cluster-eu-1
spec:
  interval: 5m0s
  ref:
    commit: 535746ae85bbe9a5e02ac76d945668f3d4e09a65
  url: https://github.com/anza-labs/manifests
