---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./environments/prod"
  prune: true
  timeout: 10m
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-generic
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  summary: "An event has occurred in the production environment."
  eventMetadata:
    env: "production"
    cluster: "eu-1"
  providerRef:
    name: discord-generic
  eventSeverity: info
  eventSources:
    - kind: "Bucket"
      name: '*'
    - kind: "GitRepository"
      name: '*'
    - kind: "Kustomization"
      name: '*'
    - kind: "HelmRelease"
      name: '*'
    - kind: "HelmChart"
      name: '*'
    - kind: "HelmRepository"
      name: '*'
    - kind: "ImageRepository"
      name: '*'
    - kind: "ImagePolicy"
      name: '*'
    - kind: "ImageUpdateAutomation"
      name: '*'
    - kind: "OCIRepository"
      name: '*'
