---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  namespace: kube-system
spec:
  interval: 5m0s
  url: https://github.com/anza-labs/manifests
  ref:
    tag: 'v2024-12-04'
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: kube-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: kube-system
  path: "./environments/prod"
  prune: true
  timeout: 10m
