---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-storage-version-migrator
spec:
  chart:
    spec:
      chart: kube-storage-version-migrator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: flux-system
      version: "0.1.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: kube-storage-version-migrator
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
      strategy: uninstall
      remediateLastFailure: true
