---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  labels:
    environment: prod
spec:
  interval: 5m0s
  url: https://github.com/anza-labs/manifests
  ref:
    commit: '535746ae85bbe9a5e02ac76d945668f3d4e09a65'
