apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 'cluster-${CLUSTER}'
resources:
- ../../base
- ./GitRepository.yaml
- ./Namespace.yaml
- ./platform-apps.yaml
patches:
- path: ./patches/infra-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    labelSelector: target=infra
- path: ./patches/workload-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    labelSelector: target=workload

