---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-storage-version-migrator
  labels:
    target: infra
spec:
  path: "./apps/platform/kube-storage-version-migrator"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  labels:
    target: infra
spec:
  path: "./apps/platform/kyverno"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  labels:
    target: workload
spec:
  path: "./apps/platform/kyverno/policies"
  dependsOn:
  - name: kyverno
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  labels:
    target: infra
spec:
  path: "./apps/platform/cert-manager"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers-cloudflare
  labels:
    target: workload
spec:
  path: "./apps/platform/cert-manager/issuers/cloudflare"
  dependsOn:
  - name: cert-manager
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubewarden-crds
  labels:
    target: infra
spec:
  path: "./apps/platform/kubewarden/crds"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubewarden-controller
  labels:
    target: infra
spec:
  path: "./apps/platform/kubewarden/controller"
  dependsOn:
  - name: kubewarden-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  labels:
    target: infra
spec:
  path: "./apps/platform/external-secrets"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-bitwarden
  labels:
    target: workload
spec:
  path: "./apps/platform/external-secrets/bitwarden"
  dependsOn:
  - name: external-secrets
  - name: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  labels:
    target: infra
spec:
  path: "./apps/platform/ingress-nginx"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  labels:
    target: infra
spec:
  path: "./apps/platform/tailscale"
  dependsOn:
  - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
spec:
  path: "./apps/platform/reloader"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  path: "./apps/platform/external-dns"
  dependsOn:
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lubelogger
spec:
  path: "./apps/public/lubelogger"
