---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamaji
  labels:
    source: helm
spec:
  chart:
    spec:
      chart: kamaji
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs-github-io-charts
        namespace: placeholder
      version: "0.1.7"
  interval: 30m0s
  timeout: 10m0s
  releaseName: kamaji
  targetNamespace: kamaji-system
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
