---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: clientId
    remoteRef:
      key: "b830888e-a946-4d40-943c-b1d300a0ceeb"
  - secretKey: clientSecret
    remoteRef:
      key: "b7aa3e3e-01fc-4c84-a330-b1d300a0f09b"
