---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  chart:
    spec:
      chart: reloader
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stakater
      version: "1.0.121"
  interval: 1m0s
  releaseName: reloader
  targetNamespace: stakater-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
