---
apiVersion: v1
kind: Namespace
metadata:
  name: k0sproject-k0smotron-infrastructure-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: k0sproject-k0smotron
  namespace: k0sproject-k0smotron-infrastructure-system
