---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: amd0.tail4d421.ts.net
    cluster.anza-labs.dev/node-env: baremetal
  name: amd0
spec:
  type: ExternalName
  externalName: placeholder.example.com
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: amd0
spec:
  clusterName: homelab-cluster
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: amd0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: amd0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: amd0
spec:
  version: v1.30.4+k0s.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: amd0
spec:
  address: amd0
  port: 22
  user: manager
  sshKeyRef:
    name: shared-key
