---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-github-io-ingress-nginx
  namespace: placeholder
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx
