# Base: configs/monitoring/prometheus
- op: add
  path: /spec/patches
  value:
    - patch: |
        - op: add
          path: /spec/values/server
          value:
            persistentVolume:
              storageClass: standard
      target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        name: prometheus
