---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-generic
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: generic-notifications
spec:
  summary: "An event has occurred in the production environment."
  eventMetadata: {}
  providerRef:
    name: discord-generic
  eventSeverity: info
  eventSources:
    - kind: "Bucket"
      name: '*'
    - kind: "GitRepository"
      name: '*'
    - kind: "Kustomization"
      name: '*'
    - kind: "HelmRelease"
      name: '*'
    - kind: "HelmChart"
      name: '*'
    - kind: "HelmRepository"
      name: '*'
    - kind: "ImageRepository"
      name: '*'
    - kind: "ImagePolicy"
      name: '*'
    - kind: "ImageUpdateAutomation"
      name: '*'
    - kind: "OCIRepository"
      name: '*'
