---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: "1.78.3"
  interval: 30m0s
  timeout: 10m0s
  releaseName: tailscale-operator
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
      remediateLastFailure: true
  valuesFrom:
  - kind: Secret
    name: tailscale-oauth
    valuesKey: clientId
    targetPath: oauth.clientId
  - kind: Secret
    name: tailscale-oauth
    valuesKey: clientSecret
    targetPath: oauth.clientSecret
