---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: "0.9.20"
  interval: 1m0s
  timeout: 10m
  releaseName: external-secrets
  targetNamespace: external-secrets
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    bitwarden-sdk-server:
      enabled: true
