---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-storage-version-migrator
spec:
  path: "./configs/core/kube-storage-version-migrator"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
spec:
  path: "./configs/core/kyverno"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
spec:
  path: "./configs/core/kyverno-policies"
  dependsOn:
  - name: kyverno
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  path: "./configs/core/cert-manager"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers-cloudflare
spec:
  path: "./configs/core/cert-manager/issuers/cloudflare"
  dependsOn:
  - name: cert-manager
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-tetragon
spec:
  path: "./configs/core/tetragon"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
spec:
  path: "./configs/core/external-secrets"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-bitwarden
spec:
  path: "./configs/core/external-secrets/bitwarden"
  dependsOn:
  - name: external-secrets
  - name: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  path: "./configs/core/ingress-nginx"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
spec:
  path: "./configs/core/tailscale"
  dependsOn:
  - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  path: "./configs/core/external-dns"
  dependsOn:
  - name: external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
spec:
  path: "./configs/core/reloader"
