apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- ./flux-apps.yaml
patches:
- path: ./patches/flux-apps-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
