---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  labels:
    environment: prod
spec:
  interval: 5m0s
  url: https://github.com/anza-labs/manifests
  ref:
    commit: '5828d5e85d499a2fc68872d3e8a22d5ea82f9008'
