apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
- ../repos
- ../../base
- ./GitRepository.yaml
- ./platform-apps.yaml
patches:
- path: ./patches/platform-apps-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
