---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scribe
spec:
  chart:
    spec:
      chart: scribe
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: flux-system
      version: "0.3.5"
  interval: 1m0s
  releaseName: scribe
  targetNamespace: scribe-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
