---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scribe
spec:
  chart:
    spec:
      chart: scribe
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: flux-system
      version: "0.3.6"
  interval: 30m0s
  timeout: 10m0s
  releaseName: scribe
  targetNamespace: scribe-system
  test:
    enable: true
    ignoreFailures: true
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
