---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scribe
spec:
  chart:
    spec:
      chart: scribe
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: flux-system
      version: "0.3.5"
  interval: 30m0s
  timeout: 10m0s
  releaseName: scribe
  test:
    enable: true
    ignoreFailures: true
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
      strategy: uninstall
      remediateLastFailure: true
