- op: replace
  path: /spec/targetNamespace
  value: infra
- op: add
  path: /spec/patches
  value:
    - patch: |
        - op: replace
          path: /spec/chart/spec/sourceRef/namespace
          value: infra
      target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
    - patch: |
        - op: replace
          path: /spec/sourceRef/namespace
          value: infra
      target:
        group: helm.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
