---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lubelogger-postgres
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: host
    remoteRef:
      key: "d0dd958a-aa7d-45a0-bfe6-b1c500b4a8e6"
  - secretKey: user
    remoteRef:
      key: "73600f13-365c-4b83-a79b-b1c500b47e3a"
  - secretKey: password
    remoteRef:
      key: "17a0ac07-6ed8-448f-b7e3-b1c500b46e2f"
  - secretKey: database
    remoteRef:
      key: "795eed39-0895-4403-84d5-b1c500b495e7"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lubelogger-mail-config
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: MailConfig__EmailServer
    remoteRef:
      key: "2d05d979-a21f-42ae-9a89-b1c500c254f6"
  - secretKey: MailConfig__EmailFrom
    remoteRef:
      key: "3af75d0e-1d02-4f9e-9fdb-b1c500b44550"
  - secretKey: MailConfig__Port
    remoteRef:
      key: "cdbca9ea-1c5b-4acd-8f8f-b1c500c2218d"
  - secretKey: MailConfig__Username
    remoteRef:
      key: "3af75d0e-1d02-4f9e-9fdb-b1c500b44550"
  - secretKey: MailConfig__Password
    remoteRef:
      key: "4164be9f-ce8a-4d46-8d98-b1c500b432d8"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lubelogger-config
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: user-hash
    remoteRef:
      key: "9af97b67-edf9-44ca-acd7-b1ed00a44870"
  - secretKey: password-hash
    remoteRef:
      key: "0b0290c0-1e18-4caf-8d67-b1ed00a47d4e"
