---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewarden-controller
spec:
  chart:
    spec:
      chart: kubewarden-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubewarden
        namespace: infra
      version: "5.1.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: kubewarden
  targetNamespace: kubewarden
  test:
    enable: true
    ignoreFailures: true
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
