---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lubelogger
spec:
  chart:
    spec:
      chart: lubelogger
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: flux-system
      version: "0.5.7"
  interval: 1m0s
  releaseName: lubelogger
  targetNamespace: anza-labs
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: Secret
    name: lubelogger-postgres
    valuesKey: host
    targetPath: postgres.host
  - kind: Secret
    name: lubelogger-postgres
    valuesKey: user
    targetPath: postgres.user
  - kind: Secret
    name: lubelogger-postgres
    valuesKey: password
    targetPath: postgres.password
  - kind: Secret
    name: lubelogger-config
    valuesKey: user-hash
    targetPath: config.userConfig.UserNameHash
  - kind: Secret
    name: lubelogger-config
    valuesKey: password-hash
    targetPath: config.userConfig.UserPasswordHash
  values:
    postgres:
      create: true
    config:
      LANG: pl_PL.UTF-8
      LC_ALL: pl_PL.UTF-8
    secret:
      create: false
      name: lubelogger-mail-config
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - host: lubelogger.anza-labs.dev
        paths:
        - pathType: Prefix
          path: /
      tls:
      - hosts:
        - lubelogger.anza-labs.dev
        secretName: lubelogger-cert
