apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- ../../apps/core
- ../../apps/capi
- ../../apps/monitoring
- ../../apps/public
patches:
- path: ./patches/lubelogger-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: lubelogger
- path: ./patches/prometheus-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: prometheus
- path: ./patches/kyverno-patch.yaml
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: kyverno
