---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger-operator
spec:
  chart:
    spec:
      chart: jaeger-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      version: "2.57.0"
  interval: 30m0s
  timeout: 10m0s
  releaseName: jaeger-operator
  targetNamespace: jaeger-system
  test:
    enable: true
    ignoreFailures: true
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
      strategy: uninstall
      remediateLastFailure: true
  values:
    rbac:
      clusterRole: true
