---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger-operator
spec:
  chart:
    spec:
      chart: jaeger-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      version: "2.57.0"
  interval: 1m0s
  releaseName: jaeger-operator
  targetNamespace: jaeger-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
      remediateLastFailure: true
  values:
    rbac:
      clusterRole: true
